// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/dialog/index.vue')['default'];
    Error: typeof import('./src/components/base/Error.vue')['default'];
    Loading: typeof import('./src/components/base/Loading.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TextOver: typeof import('./src/components/text/TextOver.vue')['default'];
  }
}

export {};
